"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Bell,Loader2,X} from "lucide-react";
import {useRouter} from "next/navigation";
import toast from "react-hot-toast";
import {notificationApi} from "@/lib/api";
import {useAuthStore} from "@/store/authStore";
type Notice={id:string;title:string;message:string;link?:string;is_read:boolean;created_at:string};
export default function NotificationBell(){
 const {isAuthenticated,user,role}=useAuthStore();
 const router=useRouter();const [items,setItems]=useState<Notice[]>([]),[unread,setUnread]=useState(0),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false);
 const container=useRef<HTMLDivElement>(null);const generation=useRef(0);
 const load=useCallback(async()=>{const current=generation.current;try{const {data}=await notificationApi.getNotifications();if(current!==generation.current)return;setItems(data.notifications||[]);setUnread(data.unreadCount||0);setFailed(false);}catch{if(current===generation.current)setFailed(true);}finally{if(current===generation.current)setLoading(false);}},[]);
 useEffect(()=>{generation.current++;setItems([]);setUnread(0);setOpen(false);if(!isAuthenticated)return;setLoading(true);void load();const refresh=()=>{if(!document.hidden)void load();};const timer=window.setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{generation.current++;window.clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[isAuthenticated,user?.id,role,load]);
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!container.current?.contains(event.target as Node))setOpen(false);};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[open]);
 if(!isAuthenticated)return null;
 const openNotice=async(notice:Notice)=>{if(busy)return;setBusy(true);try{if(!notice.is_read){await notificationApi.markAsRead(notice.id);setItems(previous=>previous.map(item=>item.id===notice.id?{...item,is_read:true}:item));setUnread(previous=>Math.max(0,previous-1));}}catch{toast.error('Could not mark the notification as read.');}finally{setBusy(false);}setOpen(false);if(notice.link?.startsWith('/')&&!notice.link.startsWith('//'))router.push(notice.link);};
 const markAll=async()=>{setBusy(true);try{await notificationApi.markAsRead('all');setItems(previous=>previous.map(item=>({...item,is_read:true})));setUnread(0);}catch{toast.error('Could not mark notifications as read.');}finally{setBusy(false);}};
 return <div ref={container} className="relative text-wood-900"><button type="button" aria-label={`Notifications${unread?`, ${unread} unread`:''}`} aria-expanded={open} onClick={()=>{setOpen(value=>!value);void load();}} className="relative p-2 rounded-lg hover:bg-wood-100"><Bell size={22}/>{unread>0&&<span className="absolute -top-1 -right-1 bg-red-600 text-white rounded-full min-w-4 px-1 text-[10px]">{unread>99?'99+':unread}</span>}</button>
 {open&&<section aria-label="Notifications" className="absolute right-0 top-full mt-2 w-[min(340px,calc(100vw-24px))] bg-white border rounded-xl shadow-xl z-[120] overflow-hidden"><header className="p-3 border-b flex items-center justify-between gap-2"><h2 className="font-semibold text-sm">Notifications</h2>{unread>0&&<button type="button" disabled={busy} onClick={()=>void markAll()} className="text-xs underline disabled:opacity-50">Mark all read</button>}<button type="button" aria-label="Close notifications" onClick={()=>setOpen(false)}><X size={16}/></button></header><div className="max-h-80 overflow-y-auto">{loading?<div className="p-5"><Loader2 className="animate-spin mx-auto" size={20}/></div>:failed?<button type="button" onClick={()=>void load()} className="p-4 text-sm w-full">Could not load notifications. Tap to retry.</button>:items.length===0?<p className="p-5 text-sm text-gray-500">No notifications yet.</p>:items.map(notice=><button type="button" key={notice.id} disabled={busy} onClick={()=>void openNotice(notice)} className={`w-full text-left p-3 border-b hover:bg-wood-100 disabled:opacity-60 ${notice.is_read?'bg-white':'bg-white'}`}><span className="block text-sm font-semibold break-words">{!notice.is_read&&<span className="inline-block w-2 h-2 bg-red-600 rounded-full mr-2"/>}{notice.title}</span><span className="block text-xs mt-1 whitespace-pre-wrap break-words">{notice.message}</span><time className="block text-[10px] text-gray-500 mt-1">{new Date(notice.created_at).toLocaleString()}</time></button>)}</div></section>}</div>;
}
