// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/commissions" | "/admin/coupons" | "/admin/dashboard" | "/admin/marketing" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/add" | "/admin/promoters" | "/admin/reports" | "/admin/return-requests" | "/admin/sellers" | "/admin/settings" | "/admin/settlements" | "/admin/users" | "/admin/website-settings" | "/admin/withdrawals" | "/admin/withdrawals/[id]" | "/auth/forgot-password" | "/auth/login" | "/auth/reset-password" | "/auth/signup" | "/auth/verify-otp" | "/contact" | "/contact-us" | "/customer/cart" | "/customer/categories" | "/customer/dashboard" | "/customer/orders" | "/customer/orders/[id]" | "/customer/orders/checkout" | "/customer/payments" | "/customer/products" | "/customer/products/[id]" | "/customer/profile" | "/customer/support" | "/customer/support/[id]" | "/customer/wishlist" | "/forgot-password" | "/merchant/analytics" | "/merchant/coupons" | "/merchant/customers" | "/merchant/dashboard" | "/merchant/instructions" | "/merchant/orders" | "/merchant/orders/[id]" | "/merchant/products" | "/merchant/profile" | "/merchant/reviews" | "/merchant/settings" | "/merchant/support" | "/merchant/wallet" | "/privacy" | "/privacy-policy" | "/promoter/dashboard" | "/refund-policy" | "/shipping-policy" | "/support/dashboard" | "/terms" | "/terms-of-service"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/auth" | "/customer" | "/merchant" | "/promoter" | "/support"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/commissions": {}
  "/admin/coupons": {}
  "/admin/dashboard": {}
  "/admin/marketing": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/add": {}
  "/admin/promoters": {}
  "/admin/reports": {}
  "/admin/return-requests": {}
  "/admin/sellers": {}
  "/admin/settings": {}
  "/admin/settlements": {}
  "/admin/users": {}
  "/admin/website-settings": {}
  "/admin/withdrawals": {}
  "/admin/withdrawals/[id]": { "id": string; }
  "/api/[[...path]]": { "path"?: string[]; }
  "/auth": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/reset-password": {}
  "/auth/signup": {}
  "/auth/verify-otp": {}
  "/contact": {}
  "/contact-us": {}
  "/customer": {}
  "/customer/cart": {}
  "/customer/categories": {}
  "/customer/dashboard": {}
  "/customer/orders": {}
  "/customer/orders/[id]": { "id": string; }
  "/customer/orders/checkout": {}
  "/customer/payments": {}
  "/customer/products": {}
  "/customer/products/[id]": { "id": string; }
  "/customer/profile": {}
  "/customer/support": {}
  "/customer/support/[id]": { "id": string; }
  "/customer/wishlist": {}
  "/forgot-password": {}
  "/merchant": {}
  "/merchant/analytics": {}
  "/merchant/coupons": {}
  "/merchant/customers": {}
  "/merchant/dashboard": {}
  "/merchant/instructions": {}
  "/merchant/orders": {}
  "/merchant/orders/[id]": { "id": string; }
  "/merchant/products": {}
  "/merchant/profile": {}
  "/merchant/reviews": {}
  "/merchant/settings": {}
  "/merchant/support": {}
  "/merchant/wallet": {}
  "/privacy": {}
  "/privacy-policy": {}
  "/promoter": {}
  "/promoter/dashboard": {}
  "/refund-policy": {}
  "/shipping-policy": {}
  "/support": {}
  "/support/dashboard": {}
  "/terms": {}
  "/terms-of-service": {}
  "/uploads/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/auth": never
  "/customer": never
  "/merchant": never
  "/promoter": never
  "/support": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
