// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/admin/commissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/commissions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/commissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/products/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/add">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/products/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/promoters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/promoters">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/promoters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/return-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/return-requests">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/return-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/sellers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/sellers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settlements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settlements">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settlements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/website-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/website-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/website-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/withdrawals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/withdrawals/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/withdrawals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/withdrawals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/withdrawals">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/withdrawals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/verify-otp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/verify-otp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-us">> = Specific
  const handler = {} as typeof import("../../../src/app/contact-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/orders/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/orders/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/products/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/products">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/support/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/support">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/wishlist">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/coupons">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/instructions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/instructions">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/instructions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/products">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/support">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/promoter/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promoter/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/promoter/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/support/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/support/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/merchant/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/merchant">> = Specific
  const handler = {} as typeof import("../../../src/app/merchant/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/promoter/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/promoter">> = Specific
  const handler = {} as typeof import("../../../src/app/promoter/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../src/app/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
