"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {CheckCircle2,Loader2,MessageCircle,RefreshCw,Send} from "lucide-react";
import toast from "react-hot-toast";
import {api} from "@/lib/api";
import {getApiError} from "@/lib/utils";
import {formatPrice,formatDate} from "@/lib/utils";
interface PriceOffer{_id:string;proposed_price:number;status:"PENDING"|"COUNTERED"|"ACCEPTED"|"REJECTED"|"SUPERSEDED"|"EXPIRED";offered_by:"customer"|"merchant";expires_at:string}
interface Message{_id:string;sender_type:"CUSTOMER"|"MERCHANT"|"ADMIN"|"SYSTEM";sender_id:string;content:string;is_offer:boolean;offer_id?:PriceOffer|null;created_at:string}
interface Conversation{_id:string;status:string;accepted_offer_id?:string|null;messages:Message[];product?:{name:string;price:number}}
interface Props{productId:string|number;productName:string;productImage:string;listedPrice:number;onClose:()=>void}
export default function BargainPanel({productId,productName,productImage,listedPrice,onClose}:Props){
 const [conversation,setConversation]=useState<Conversation|null>(null);const [loading,setLoading]=useState(true);const [inputText,setInputText]=useState("");const [offerPrice,setOfferPrice]=useState("");const [offerMode,setOfferMode]=useState(false);const [sending,setSending]=useState(false);const [actingOn,setActingOn]=useState("");const endRef=useRef<HTMLDivElement>(null);
 const refresh=useCallback(async(id:string,silent=false)=>{try{const {data}=await api.get(`/conversations/${id}`);setConversation(data);}catch(error){if(!silent)toast.error(getApiError(error));}},[]);
 useEffect(()=>{let live=true;let id="";const init=async()=>{try{const {data}=await api.post("/conversations/init",{product_id:String(productId)});id=data._id;if(live)setConversation(data);if(live)await refresh(id);}catch(error){if(live)toast.error(getApiError(error));}finally{if(live)setLoading(false);}};void init();return()=>{live=false;};},[productId,refresh]);
 useEffect(()=>{if(!conversation?._id)return;const timer=window.setInterval(()=>void refresh(conversation._id,true),5000);return()=>window.clearInterval(timer);},[conversation?._id,refresh]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[conversation?.messages.length]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!conversation||sending)return;const content=inputText.trim();const price=Number(offerPrice);if(offerMode&&(!Number.isFinite(price)||price<=0||price>listedPrice)){toast.error(`Enter an amount up to ${formatPrice(listedPrice)}`);return;}if(!offerMode&&!content)return;setSending(true);try{const {data}=offerMode?await api.post(`/conversations/${conversation._id}/offers`,{proposed_price:price,message:content}):await api.post(`/conversations/${conversation._id}/messages`,{content});setConversation(data);setInputText("");setOfferPrice("");setOfferMode(false);}catch(error){toast.error(getApiError(error));}finally{setSending(false);}};
 const act=async(offerId:string,action:"accept"|"reject")=>{setActingOn(offerId);try{const {data}=await api.post(`/conversations/offers/${offerId}/${action}`);setConversation(data);toast.success(action==="accept"?"Offer accepted. The agreed price applies to your next order within 7 days.":"Offer declined");}catch(error){toast.error(getApiError(error));}finally{setActingOn("");}};
 return <div className="fixed top-0 right-0 h-dvh z-[100] w-full max-w-full sm:w-[450px] bg-white shadow-2xl flex flex-col font-inter text-wood-900 border-l border-wood-200">
  <header className="p-4 border-b flex items-center justify-between bg-white"><div><h2 className="font-playfair font-semibold text-xl">Negotiate this price</h2><p className="text-xs text-wood-500">Chat directly with the store owner</p></div><button onClick={onClose} aria-label="Close negotiation" className="px-3 py-2 hover:bg-wood-200 rounded">Close</button></header>
  <div className="p-4 border-b flex gap-4 items-center"><img src={productImage} alt="" className="w-14 h-14 object-cover rounded-md border"/><div className="min-w-0"><h3 className="font-semibold text-sm truncate">{productName}</h3><p className="text-xs mt-1">Listed price: <strong>{formatPrice(listedPrice)}</strong></p></div></div>
  {conversation?.accepted_offer_id&&<p className="px-4 py-3 bg-green-50 text-green-900 text-sm">Agreed price will apply automatically to this item on your next order for 7 days.</p>}
  <div className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4 bg-white/50">{loading?<div className="h-full flex items-center justify-center"><Loader2 className="animate-spin"/></div>:!conversation?<p role="alert">The negotiation could not be opened. Close this panel and try again.</p>:conversation.messages.length===0?<div className="text-center py-10"><MessageCircle className="mx-auto mb-2 text-wood-400"/><p className="text-sm font-medium">Start the conversation</p><p className="text-xs mt-1 text-wood-500">Ask about the item or make a price offer.</p></div>:conversation.messages.map(msg=>{const isSystem=msg.sender_type==="SYSTEM";const isOffer=msg.is_offer&&msg.offer_id;const myRole=msg.sender_type==="CUSTOMER";const recipientCanRespond=isOffer&&msg.offer_id!.status==="PENDING"&&msg.offer_id!.offered_by==="merchant";return isSystem?<div key={msg._id} className="text-center text-xs text-wood-600 my-4">{msg.content}</div>:<div key={msg._id} className={`flex flex-col max-w-[90%] ${myRole?"ml-auto items-end":"mr-auto items-start"}`}><div className={`p-3 rounded-2xl ${myRole?"bg-wood-800 text-white":"bg-white border shadow-sm"}`}><p className="text-[10px] uppercase opacity-70 mb-1">{myRole?"Customer":"Store"}</p>{msg.content&&<p className="text-sm whitespace-pre-wrap">{msg.content}</p>}{isOffer&&<div className="mt-2 p-3 rounded-xl border bg-white/10"><p className="text-[10px] uppercase">{msg.offer_id!.offered_by==="customer"?"Customer’s offer":"Store owner’s counteroffer"}</p><p className="text-lg font-bold">{formatPrice(msg.offer_id!.proposed_price)}</p><p className="text-[10px] mt-1">{msg.offer_id!.status.toLowerCase()}{msg.offer_id!.status==="PENDING"?` · Expires ${formatDate(msg.offer_id!.expires_at)}`:""}</p>{recipientCanRespond&&<div className="flex gap-2 mt-2"><button disabled={!!actingOn} onClick={()=>void act(msg.offer_id!._id,"accept")} className="bg-green-700 text-white text-xs px-3 py-2 rounded disabled:opacity-50">{actingOn===msg.offer_id!._id?<Loader2 className="animate-spin" size={14}/>:<><CheckCircle2 className="inline mr-1" size={14}/>Accept</>}</button><button disabled={!!actingOn} onClick={()=>void act(msg.offer_id!._id,"reject")} className="border text-xs px-3 py-2 rounded disabled:opacity-50">Decline</button></div>}</div>}</div><span className="text-[10px] text-wood-400 mt-1">{formatDate(msg.created_at)}</span></div>;})}<div ref={endRef}/></div>
  <footer className="p-3 sm:p-4 bg-white border-t pb-[max(0.75rem,env(safe-area-inset-bottom))]">{offerMode&&<div className="mb-3 p-3 bg-white rounded-xl border flex items-center gap-2"><span>₹</span><input min="1" max={listedPrice} step="0.01" type="number" aria-label="Offer amount" placeholder="Your price" value={offerPrice} onChange={e=>setOfferPrice(e.target.value)} className="flex-1 bg-transparent text-sm focus:outline-none"/><button type="button" onClick={()=>setOfferMode(false)} className="text-xs underline">Cancel</button></div>}<form onSubmit={submit} className="flex items-center gap-2">{!offerMode&&<button type="button" onClick={()=>setOfferMode(true)} className="bg-wood-100 text-wood-800 text-xs font-semibold px-3 py-3 rounded-full whitespace-nowrap">Make offer</button>}<input maxLength={2000} value={inputText} onChange={e=>setInputText(e.target.value)} placeholder={offerMode?"Add a message (optional)…":"Ask the store owner a question…"} className="flex-1 min-w-0 bg-white border rounded-full px-4 py-3 text-sm focus:outline-none"/><button disabled={sending||(!inputText.trim()&&!(offerMode&&offerPrice))} aria-label={offerMode?"Send price offer":"Send message"} type="submit" className="bg-wood-900 text-white p-3 rounded-full disabled:opacity-50">{sending?<Loader2 size={18} className="animate-spin"/>:<Send size={18}/>}</button></form><p className="mt-2 text-[10px] text-wood-500">An accepted offer applies once to this product, expires after 7 days and does not collect payment.</p></footer>
 </div>;
}
