const express=require('express');const cors=require('cors');const mongoose=require('mongoose');const path=require('path');
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'8mb'}));
app.use(cors({origin:(origin,cb)=>{const allowed=(process.env.FRONTEND_URL||'http://localhost:3000').split(',').map(s=>s.trim());if(!origin||allowed.includes(origin)||origin==='http://127.0.0.1:3000')cb(null,true);else cb(Object.assign(new Error('Origin is not allowed'),{status:403}));}}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');next();});
app.get('/api/health',(req,res)=>res.status(mongoose.connection.readyState===1?200:503).json({status:mongoose.connection.readyState===1?'ok':'unavailable',database:mongoose.connection.readyState===1?'connected':'disconnected',payment_mode:'local_pending'}));
app.get('/api/v1',(req,res)=>res.json({version:'1.1',payment_mode:'local_pending'}));
app.use('/uploads',express.static(path.resolve(__dirname,'../uploads'),{dotfiles:'deny',setHeaders:res=>res.setHeader('Content-Security-Policy',"default-src 'none'")}));
app.use('/api/v1/auth',require('./routes/authRoutes'));
app.use('/api/v1/products',require('./routes/productRoutes'));
app.use('/api/v1/admin',require('./routes/adminRoutes'));
app.use('/api/v1/merchant',(req,res)=>res.status(410).json({error:'This portal has been retired. Store management is available to administrators.'}));
app.use('/api/v1',require('./routes/serviceRoutes'));
app.use('/api/v1',require('./routes/commerceRoutes'));
app.use((req,res)=>res.status(404).json({error:'Endpoint not found'}));
app.use((err,req,res,next)=>{
 const status=err.status||(err.code===11000?409:['ValidationError','CastError','SyntaxError'].includes(err.name)?400:500);
 const message=err.code===11000?'This record already exists':status>=500?'The service could not complete the request. Please retry.':err.message;
 if(status>=500)console.error('Request failed:',req.method,req.path,err.name,err.message);
 res.status(status).json({error:message,detail:message});
});
module.exports=app;
