const router=require('express').Router();const Product=require('../models/Product');const User=require('../models/User');
const {Order,Coupon,Review,Setting}=require('../models/Commerce');const {authenticate,roles}=require('../middleware/auth');const {asyncRoute:wrap,fail,pick,id,plain,page}=require('../lib/http');
router.use(authenticate,roles('merchant','admin'));
const profile=u=>({id:String(u._id),user_id:String(u._id),business_name:u.full_name+' Store',commission_rate:0,is_approved:false,created_at:u.createdAt,...(u.merchant_profile||{})});
router.get('/profile',(req,res)=>res.json(profile(req.user)));
for(const method of ['post','put'])router[method]('/profile',wrap(async(req,res)=>{req.user.merchant_profile={...profile(req.user),...pick(req.body,['business_name','business_description','gstin','logo_url','phone','address'])};await req.user.save();res.json(profile(req.user));}));
router.get('/analytics',wrap(async(req,res)=>{const orders=await Order.find({'items.merchant_id':String(req.user._id)});const paid=orders.filter(o=>o.payment_status==='paid');const total=paid.reduce((sum,o)=>sum+o.items.filter(i=>i.merchant_id===String(req.user._id)).reduce((n,i)=>n+i.total_price,0),0);res.json({total_revenue:total,total_earnings:total,available_payout:0,total_orders:orders.length,total_products:await Product.countDocuments({merchant:req.user._id}),daily_sales:[]});}));
router.get('/wallet',(req,res)=>res.json({available_balance:0,total_withdrawn:0,message:'Local orders are unpaid; there are no withdrawable funds.'}));
router.post('/withdraw',(req,res)=>res.status(409).json({error:'No withdrawable balance: local orders have payment pending.'}));
for(const resource of ['withdrawals','settlements','commissions'])router.get('/'+resource,wrap(async(req,res)=>res.json(page((await Setting.find({key:{$regex:'^ledger:'+resource+':'},'value.user_id':String(req.user._id)})).map(r=>r.value),req.query))));
router.get('/coupons',wrap(async(req,res)=>res.json((await Coupon.find({is_active:true})).map(plain))));
router.get('/reviews',wrap(async(req,res)=>{const products=await Product.find({merchant:req.user._id}).select('_id');const reviews=await Review.find({product:{$in:products.map(p=>p._id)}}).populate('user','full_name').populate('product','name');res.json({...page(reviews.map(r=>({...plain(r),customer_name:r.user?.full_name,product_name:r.product?.name})),req.query),average_rating:reviews.length?reviews.reduce((n,r)=>n+r.rating,0)/reviews.length:0});}));
router.get('/customers',wrap(async(req,res)=>{const orders=await Order.find({'items.merchant_id':String(req.user._id)}).populate('customer');const customers=new Map();for(const o of orders){if(!o.customer)continue;const key=String(o.customer._id);const c=customers.get(key)||{id:key,full_name:o.customer.full_name,email:o.customer.email,total_orders:0,total_spent:0,created_at:o.customer.createdAt};c.total_orders++;if(o.payment_status==='paid')c.total_spent+=o.items.filter(i=>i.merchant_id===String(req.user._id)).reduce((n,i)=>n+i.total_price,0);customers.set(key,c);}res.json(page([...customers.values()],req.query));}));
router.post('/products/bulk-upload',wrap(async(req,res)=>{
 const csv=String(req.body.csvData||'');if(!csv.trim())fail(400,'CSV is empty');
 // RFC-style quoted values, including commas and newlines inside a cell.
 const rows=[];let row=[],value='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&csv[i+1]==='\n')i++;row.push(value);if(row.some(Boolean))rows.push(row);row=[];value='';}else value+=c;}if(quoted)fail(400,'Unclosed CSV quote');if(value||row.length){row.push(value);rows.push(row);}const headers=(rows.shift()||[]).map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers.includes('name')||!headers.includes('price'))fail(400,'CSV requires name and price columns');if(rows.length>500)fail(400,'Import at most 500 products at a time');
 const docs=rows.map(values=>{const raw=Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()]));for(const k of ['price','stock_quantity','compare_price'])if(raw[k])raw[k]=Number(raw[k]);if(raw.images)raw.images=raw.images.split('|');for(const k of ['is_active','is_featured','allow_pre_order'])if(raw[k])raw[k]=raw[k]==='true';return new Product({...require('./productRoutes').normalize(raw),merchant:req.user._id,is_approved:req.user.role==='admin'});});
 for(const doc of docs)await doc.validate();await Product.insertMany(docs);res.status(201).json({success:true,inserted:docs.length});
}));
module.exports=router;
