"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {RefreshCw,Send,Loader2,CheckCircle2,Inbox} from "lucide-react";
import toast from "react-hot-toast";
import {api} from "@/lib/api";
import {getApiError} from "@/lib/utils";
import {formatDate,formatPrice} from "@/lib/utils";
type Offer={_id:string;proposed_price:number;status:string;offered_by:'customer'|'merchant';expires_at:string};
type Message={_id:string;sender_type:string;content:string;is_offer:boolean;offer_id?:Offer|null;created_at:string};
type Enquiry={_id:string;status:string;product:{id:string;name:string;price:number}|null;customer:{id:string;full_name:string;email:string}|null;messages:Message[];accepted_offer_id?:string|null};
export default function MerchantEnquiriesPage(){
 const [items,setItems]=useState<Enquiry[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[counter,setCounter]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async(silent=false)=>{try{const {data}=await api.get('/merchant/conversations');setItems(data);setSelected(current=>current&&data.some((x:Enquiry)=>x._id===current)?current:data[0]?._id||'');}catch(e){if(!silent)toast.error(getApiError(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),5000);return()=>window.clearInterval(timer);},[load]);
 const active=items.find(x=>x._id===selected);const replace=(u:Enquiry)=>setItems(prev=>[u,...prev.filter(x=>x._id!==u._id)]);
 const send=async(e:FormEvent)=>{e.preventDefault();if(!active||!message.trim())return;setBusy('message');try{const {data}=await api.post(`/conversations/${active._id}/messages`,{content:message.trim()});replace(data);setMessage('');}catch(err){toast.error(getApiError(err));}finally{setBusy('');}};
 const counterOffer=async(e:FormEvent)=>{e.preventDefault();if(!active?.product)return;const price=Number(counter);if(!Number.isFinite(price)||price<=0||price>active.product.price){toast.error('Enter a positive price no higher than the listed price');return;}setBusy('offer');try{const {data}=await api.post(`/conversations/${active._id}/offers`,{proposed_price:price});replace(data);setCounter('');toast.success('Counteroffer sent');}catch(err){toast.error(getApiError(err));}finally{setBusy('');}};
 const decide=async(id:string,action:'accept'|'reject')=>{setBusy(id);try{const {data}=await api.post(`/conversations/offers/${id}/${action}`);replace(data);toast.success(action==='accept'?'Offer accepted; it is valid for the customer’s next order for 7 days.':'Offer declined');}catch(e){toast.error(getApiError(e));}finally{setBusy('');}};
 return <section className="space-y-5 text-wood-900"><header className="flex flex-wrap justify-between items-center gap-3"><div><h1 className="font-playfair text-3xl font-bold">Price enquiries</h1><p className="text-sm text-wood-600 mt-1">Reply to customer questions, accept offers or make a counteroffer.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 border rounded-lg px-4 py-2"><RefreshCw size={16}/>Refresh</button></header>
 <div className="grid lg:grid-cols-[320px_1fr] gap-5 min-h-[560px]"><aside className="bg-white border rounded-2xl overflow-hidden"><h2 className="font-semibold p-4 border-b">Customer conversations ({items.length})</h2>{loading?<div className="p-8 text-center"><Loader2 className="animate-spin mx-auto"/></div>:items.length===0?<div className="p-8 text-center text-sm text-wood-600"><Inbox className="mx-auto mb-3"/><p>No enquiries yet.</p></div>:items.map(c=><button key={c._id} onClick={()=>setSelected(c._id)} className={`w-full text-left p-4 border-b hover:bg-wood-50 ${selected===c._id?'bg-wood-50':''}`}><span className="block font-semibold">{c.customer?.full_name||'Customer'}</span><span className="block text-xs text-wood-600 mt-1">{c.product?.name||'Product unavailable'}</span><span className="block text-xs text-wood-500 mt-1 line-clamp-1">{c.messages.at(-1)?.content||'New enquiry'}</span></button>)}</aside>
 {!active?<div className="bg-white border rounded-2xl grid place-items-center p-8 text-center"><div><Inbox className="mx-auto mb-3 text-wood-400"/><p className="font-semibold">Select an enquiry to reply</p><p className="text-sm text-wood-600 mt-1">New offers and messages appear automatically.</p></div></div>:<article className="bg-white border rounded-2xl flex flex-col min-h-[560px]"><header className="p-4 border-b flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{active.product?.name||'Product'}</h2><p className="text-xs text-wood-600">{active.customer?.full_name} · Listed at {formatPrice(active.product?.price||0)}</p></div><div className="text-xs text-right text-wood-600">{active.customer?.email}<br/>Conversation: {active.status}</div></header>
 {active.accepted_offer_id&&<p className="px-4 py-3 bg-green-50 text-green-900 text-sm">Both sides agreed on a price. It applies once at checkout for 7 days.</p>}
 <div className="flex-1 overflow-y-auto p-4 space-y-3">{active.messages.map(m=><div key={m._id} className={`max-w-[90%] rounded-xl p-3 ${m.sender_type==='MERCHANT'?'ml-auto bg-wood-800 text-white':m.sender_type==='SYSTEM'?'mx-auto text-center bg-green-50 text-green-900':'mr-auto bg-wood-50 border'}`}>{m.sender_type!=='SYSTEM'&&<div className="text-[10px] uppercase opacity-70 mb-1">{m.sender_type==='MERCHANT'?'You':'Customer'}</div>}{m.content&&<p className="text-sm whitespace-pre-wrap">{m.content}</p>}{m.is_offer&&m.offer_id&&<div className="mt-2 border-t border-current/20 pt-2"><strong>{m.offer_id.offered_by==='customer'?'Customer offer':'Your counteroffer'}: {formatPrice(m.offer_id.proposed_price)}</strong><p className="text-xs mt-1">{m.offer_id.status.toLowerCase()}{m.offer_id.status==='PENDING'?` · Expires ${formatDate(m.offer_id.expires_at)}`:''}</p>{m.offer_id.status==='PENDING'&&m.offer_id.offered_by==='customer'&&<div className="flex gap-2 mt-2"><button disabled={!!busy} onClick={()=>void decide(m.offer_id!._id,'accept')} className="bg-green-700 text-white rounded px-3 py-1.5 text-xs disabled:opacity-50">{busy===m.offer_id!._id?<Loader2 className="animate-spin" size={14}/>:<><CheckCircle2 className="inline mr-1" size={14}/>Accept price</>}</button><button disabled={!!busy} onClick={()=>void decide(m.offer_id!._id,'reject')} className="border border-current rounded px-3 py-1.5 text-xs">Decline</button></div>}</div>}<p className="text-[10px] mt-2 opacity-60">{formatDate(m.created_at)}</p></div>)}</div>
 {active.status!=='closed'&&<footer className="border-t p-4 space-y-3"><form onSubmit={counterOffer} className="flex gap-2"><input type="number" min="0.01" max={active.product?.price||0} step="0.01" value={counter} onChange={e=>setCounter(e.target.value)} placeholder="Counteroffer in ₹" aria-label="Counteroffer price" className="border rounded-lg p-2 flex-1 min-w-0"/><button disabled={!!busy} className="bg-wood-100 px-4 py-2 rounded-lg text-sm disabled:opacity-50">{busy==='offer'?<Loader2 className="animate-spin"/>:'Send counteroffer'}</button></form><form onSubmit={send} className="flex gap-2"><input maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Reply to the customer…" className="border rounded-full px-4 py-3 flex-1 min-w-0 text-sm"/><button disabled={!!busy||!message.trim()} aria-label="Send reply" className="bg-wood-900 rounded-full text-white p-3 disabled:opacity-50">{busy==='message'?<Loader2 className="animate-spin" size={18}/>:<Send size={18}/>}</button></form></footer>}</article>}</div></section>;
}
