"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import toast from 'react-hot-toast';
import {addressApi,orderApi} from '@/lib/api';
import {useCartStore} from '@/store/cartStore';
import {Address} from '@/types';
import {formatPrice,getApiError} from '@/lib/utils';
const schema=z.object({full_name:z.string().min(2),phone:z.string().regex(/^[6-9]\d{9}$/,'Enter a 10-digit mobile number'),line1:z.string().min(5),city:z.string().min(2),state:z.string().min(2),pincode:z.string().regex(/^[1-9]\d{5}$/,'Enter a 6-digit PIN code')});
type Form=z.infer<typeof schema>;
export default function CheckoutPage(){
 const router=useRouter();const {cart,fetchCart,resetCart}=useCartStore();const [addresses,setAddresses]=useState<Address[]>([]);const [selected,setSelected]=useState<string>('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [showForm,setShowForm]=useState(false);const [code,setCode]=useState('');const [coupon,setCoupon]=useState('');const [discount,setDiscount]=useState(0);const key=useRef('');
 const {register,handleSubmit,reset,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema)});
 useEffect(()=>{key.current=sessionStorage.getItem('checkout-key')||crypto.randomUUID();sessionStorage.setItem('checkout-key',key.current);Promise.all([fetchCart(),addressApi.list().then(({data})=>{setAddresses(data.items);setSelected(String(data.items[0]?.id||''));setShowForm(!data.items.length);})]).catch(e=>setError(getApiError(e))).finally(()=>setLoading(false));},[fetchCart]);
 const saveAddress=async(data:Form)=>{setSaving(true);try{const {data:address}=await addressApi.create({...data,label:'Home',country:'India'});setAddresses(v=>[...v,address]);setSelected(String(address.id));setShowForm(false);reset();}catch(e){toast.error(getApiError(e));}finally{setSaving(false);}};
 const applyCoupon=async()=>{try{const {data}=await orderApi.validateCoupon({code});setDiscount(data.discount_amount);setCoupon(code.toUpperCase());toast.success('Coupon applied');}catch(e){setCoupon('');setDiscount(0);toast.error(getApiError(e));}};
 const placeOrder=async()=>{if(!selected||saving)return;setSaving(true);setError('');try{const {data}=await orderApi.create({address_id:selected,coupon_code:coupon||undefined,request_key:key.current});sessionStorage.removeItem('checkout-key');resetCart();toast.success('Order saved — payment pending');router.push('/customer/orders/'+data.id);}catch(e){setError(getApiError(e));}finally{setSaving(false);}};
 if(loading)return <div className="p-12 text-center" role="status">Loading checkout…</div>;
 const shipping=cart.subtotal>=100000?0:cart.items.length?1500:0;
 return <main className="max-w-5xl mx-auto p-0 sm:p-3 space-y-6"><h1 className="font-playfair text-3xl font-bold">Checkout</h1><p className="bg-amber-50 border border-amber-200 rounded-xl p-4">Local testing: this saves your order with payment pending. No money is collected.</p>{error&&<p role="alert" className="text-red-700 bg-red-50 p-4">{error}</p>}{!cart.items.length?<p>Your cart is empty. <a href="/customer/products" className="underline">Browse products</a></p>:<div className="grid md:grid-cols-2 gap-6"><section className="bg-white rounded-xl p-4 sm:p-6 space-y-4"><h2 className="text-xl font-bold">Delivery address</h2>{addresses.map(a=><label key={a.id} className="flex gap-3 border p-3 rounded"><input type="radio" name="address" checked={selected===String(a.id)} onChange={()=>setSelected(String(a.id))}/><span>{a.full_name}<br/>{a.line1}, {a.city}, {a.state} {a.pincode}<br/>{a.phone}</span></label>)}<button className="underline" onClick={()=>setShowForm(!showForm)}>Add a delivery address</button>{showForm&&<form onSubmit={handleSubmit(saveAddress)} className="space-y-3">{(['full_name','phone','line1','city','state','pincode'] as const).map(field=><label key={field} className="block capitalize">{field.replace('_',' ')}<input {...register(field)} className="block border rounded p-2 w-full"/>{errors[field]&&<span className="text-red-700 text-sm">{errors[field]?.message}</span>}</label>)}<button disabled={saving} className="bg-wood-900 text-white px-4 py-2 rounded">Save address</button></form>}</section><section className="bg-white rounded-xl p-4 sm:p-6 space-y-4"><h2 className="text-xl font-bold">Order summary</h2>{cart.items.map(i=><div key={i.id} className="flex justify-between gap-3 break-words"><span>{i.product.name} × {i.quantity}</span><span>{formatPrice(i.product.price*i.quantity)}</span></div>)}<div className="flex gap-2"><input aria-label="Coupon code" value={code} onChange={e=>setCode(e.target.value)} placeholder="Coupon code" className="border p-2 rounded min-w-0 flex-1 w-full"/><button onClick={applyCoupon} className="underline">Apply</button></div><p>Subtotal: {formatPrice(cart.subtotal)}</p><p>Delivery: {formatPrice(shipping)}</p>{coupon&&<p>Discount ({coupon}): −{formatPrice(discount)}</p>}<p className="font-bold text-xl">Estimated total: {formatPrice(cart.subtotal+shipping-discount)}</p><p className="text-sm">Availability, discounts and final totals are checked by the server when you place the order.</p><button disabled={saving||!selected} onClick={placeOrder} className="w-full bg-wood-900 text-white px-5 py-3 rounded-xl disabled:opacity-50">{saving?'Saving order…':'Place order — payment pending'}</button></section></div>}</main>;
}
